# Generated by Django 5.1.6 on 2025-02-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_comment_profile_replycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.CharField(blank=True, max_length=132, null=True),
        ),
    ]
