# Generated by Django 5.1.6 on 2025-02-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_blog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='custom_choices',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_recurring',
            field=models.BooleanField(blank=True, choices=[('Daily', 'daily'), ('Monthly', 'monthly'), ('Weekly', 'weekly')], default=False, null=True),
        ),
    ]
