# Generated by Django 5.0.7 on 2025-03-28 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_blogpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='replycomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='replycomment',
            name='blog',
        ),
        migrations.AlterUniqueTogether(
            name='savedblog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='savedblog',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='savedblog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='comment',
        ),
        migrations.AddField(
            model_name='blog',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='ReplyComment',
        ),
        migrations.DeleteModel(
            name='SavedBlog',
        ),
    ]
