# Generated by Django 5.0.7 on 2025-03-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_remove_comment_blog_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_recurring',
        ),
    ]
