# Generated by Django 5.0.7 on 2025-04-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_profile_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
